# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Lanssie
email: lanssie.ma@gmail.com
description: > 
  Personal website of Lanssie
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://lanssie.com" # the base hostname & protocol for your site
# twitter_username: # Add  Twitter username
github_username: lanseafood

# Build settings
markdown: kramdown
theme: minima

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
